### PR TITLE
Social sharing on level completion

### LINKED ISSUE #226: Level complete message briefly visible on load
https://github.com/everypolitician/gender-balance/pull/209 changed to hiding the level complete message with javascript, but this means that the message is very briefly visible on page load. Ideally we could just add a class to the level complete message to hide it if we knew there were cards to show on top of it, rather than hiding it with javascript.

### LINKED ISSUE #237: Social Media sharing at end of level
It should be really easy to share things like this:
https://twitter.com/edent/status/627399435790716928

### PR DESCRIPTION
**Pull request by zarino**
Fixes #237 – adds Twitter share link to the "trophy" screen.

screen shot 2015-08-06 at 11 10 53

Also improves the spacing on tiny screens.

@tmtmtmtm @MyfanwyNixon @chrismytton – I've not thought very much about the text. Over to you for that! Also, we can attach an image to the tweet if you know what it should show/say.

### CODE REVIEW

**Comment by MyfanwyNixon** [comment]
I have a bias against the word 'awesome' that I believe is not shared by my colleagues, so you may want to ignore my choices on this one. But my preference would be for:

> Amazing work -- thank you!

And very small tweaks to the following sentence:

> You've just completed [name of parliament]. There's/There are x more level/s to play.

Personally I prefer numbers to be written out in full if they're below 10, but that *really is* a personal preference.

And then for a tweet, how about the ubiquitous 'grumpy men in politics' shot we've used everywhere else, with the message: "I just sorted the women from the boys on level x of the [name of country] parliament. Join me at gender-balance.org"

This strikes me as something people might like to share more on Facebook - any plans there?

**Comment by zarino** [comment]
But @MyfanwyNixon!!

Everything is Awesome

**Comment by tmtmtmtm** [comment]
I definitely share the bias against 'awesome', but that's a fight I've also pretty much given up on as a lost cause…

**Comment by MyfanwyNixon** [comment]
Ha ha :D

**Comment by zarino** [comment]
> I definitely share the bias against 'awesome'

Remember, it *is* only *one* of *22* messages we randomly show people:

https://github.com/everypolitician/gender-balance/blob/f43e781fc7daef1a263bc56a71bbc50cb622d61f/config/motivational_quotes.yml#L8

**Comment by MyfanwyNixon** [comment]
oh well in that case, ignore me!

**Comment by chrismytton** [comment]
I've updated and force pushed this branch to remove the changes for hiding the level complete message with CSS. This branch now *only* contains the change to add a "Tweet this" button.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon's current text: "I just sorted the women from the boys on level x of the [name of country] parliament."

Issues:
* We can't easily use [name of country] as an adjective — it works in some cases, but not in others (e.g. "the France parliament"
* We shouldn't really use the word 'parliament' either — using that for lots of countries would seem as odd as saying "The UK National Assembly"
* What would the "x" in "level X" be? Just an increasing number? Or somehow tied to the name of the period?

[NB: we can't really use the "[name of country][name of legislature]" construct from @zarino's version either: it's fairly ugly in lots of cases (with the same noun-as-adjective problem), and and involves duplication in others ("I just completed Curaçao Estates of Curaçao").]

**Comment by zarino** [comment]
@tmtmtmtm It seems like we keep facing this problem of basically not having a shorthand, "native speaker" way of referring to a legislature. Could this be something that EveryPolitician datasets contain? Because, speaking as someone who is building websites/apps on top of EP data, that's totally something that would make my life easier.

**Comment by tmtmtmtm** [comment]
@zarino, potentially yes, if we could work out what it should look like… Any suggestions?

**Pull request closed without merging**
