### PR TITLE
New logged-in and anonymous homepages

### LINKED ISSUE #103: Order of text on homepage (not logged in)
screen shot 2015-07-17 at 11 52 50

The buttons currently interrupt the flow of the text.

### LINKED ISSUE #169: Add a 'login' button
At the minute the only place with a Login button is the end of the onboarding game. This means every time you log out you need to go through it again, which isn't particularly friendly.

We should either offer login directly on the homepage, or, if that's too cluttered, we could potentially add it to the onboarding game itself — it's only extra click after hitting 'Play', but it's not as bad as having to go through the whole thing again.

### PR DESCRIPTION
**Pull request by zarino**
The rejigged layout fixes #103. The login link fixes #169.

The little screenshot in the green section is animated.

screen shot 2015-07-28 at 18 15 04

@chrismytton – I've hard-coded the leaderboard for now. Wasn't sure whether you wanted me to just pull in the names as we do [elsewhere in app.rb](https://github.com/everypolitician/gender-balance/blob/b8b447ad993024eccf14a0fe6a1dd283b066faa6/app.rb#L151-L154) or whether this is an opportunity to DRY up that bit of the code?

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
I'm not sure we need a separate /leaderboard page if we're going to include its entire contents on the homepage anyway. When we get to the point where we have multiple versions of the leaderboard, then having a separate page, and abstracting the logic out to avoid duplication would make sense. But for now I've just replaced it into here (though there's a certain amount of duplication across both templates that we might want to abstract out into partials at some point).

**Comment by tmtmtmtm** [comment]
@zarino is there anything else stopping this from going live now? If not, @chrismytton should give it a once-over and then deploy…

**Comment by zarino** [comment]
> I'm not sure we need a separate /leaderboard page

:+1:

**Comment by chrismytton** [comment]
:+1: :sparkles:

**Pull request merged**
