### PR TITLE
Add basic copy to the report page

### PR DESCRIPTION
**Pull request by chrismytton**
This can be expanded over time but for now I've just included the suggestion from @MyfanwyNixon in https://github.com/everypolitician/gender-balance/pull/337#issuecomment-228367253.

screen shot 2016-07-01 at 11 02 12

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon I think we definitely need to expand on this a bit. This is a page that we would expect users to share links to, so this text needs to be something that works if this is the first page a user ever sees on GB.

**Comment by tmtmtmtm** [comment]
> This data was generated by the Gender Balance project

@MyfanwyNixon: lots of the data _didn't_ come from Gender Balance, so we can't really say this. This is the page that simply shows the current state of what we know about the gender balance for a legislature — over time where possible, and also broken down by the political parties/factions/groups. That will then, in turn, lead naturally to people playing the game to fill in gaps: whether because we're still missing data for this country, or because they want to see the equivalent figures for other countries where we don't yet have data. 

We don't mention other sources on the site at the minute, because until this change goes live Gender-Balance.org is _only_ the game. This is the start of us switching the focus around from "we have very little gender data, play this game to help us gather some" to "Look at all this gender data (and please play this game to help us get the rest)"

**Comment by MyfanwyNixon** [comment]
> lots of the data didn't come from Gender Balance, so we can't really say this.

Ah, and this was me trying to provide wording to be a bit vaguer about it, but yes, now I look again 'generated' does seem a bit more specific than I intended. I was trying to convey that 'the Gender Balance team aggregated the data'.

How about:

> This is the what we know about the gender breakdown of politicians in [this country], free for anyone to download and use -- or find data on the gender balance of politicians across the world [here].
> This data comes from a variety of sources, including the Gender Balance game. [Find out more].

Or drop the last line if you don't think it's so important.

**Comment by tmtmtmtm** [comment]
Looks good to me! Thanks @MyfanwyNixon

**Pull request merged**
