### PR TITLE
Add standard footer

### PR DESCRIPTION
**Pull request by wrightmartin**
Adds the standard mySociety footer to GenderBalance.

Please check that the links and the blurb are appropriate for the project

screen shot 2016-06-07 at 12 00 26

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
I've rebased this over master, so we shoudl now have the correct travis config

**Comment by tmtmtmtm** [comment]
@davewhiteland / @MyfanwyNixon thoughts on the text/links etc for this one?

**Comment by davewhiteland** [comment]
Seems OK to me: Gender Balance is something of a special case, since it's more like a single page anyway than a browsable website; so linking to About and EveryPolitician seems like enough. 👍

**Comment by MyfanwyNixon** [comment]
> Crowdsourcing a single, reliable source for gender data of politicians in every country in the world, and for the world as a whole

It took me a while to understand that 'for the world as a whole' didn't mean 'for the benefit of the world'. Maybe a better attempt would be:

> Crowdsourcing a single, reliable source for global and country-specific data on the gender of politicians.

It's not easy, but I think that's an improvement!

Links: Fine to have those two, but the link to EveryPolitician needs some context. If we can put text other than the links in, I'd go for:

- **About** [Find out more about Gender Balance]
- Gender Balance **contributes data** to the [EveryPolitician] project

**Comment by tmtmtmtm** [comment]
>> Crowdsourcing a single, reliable source for global and country-specific data on the gender of politicians.

> It's not easy, but I think that's an improvement!

Why are we even differentiating the two at all? I'm not convinced it really adds much…

**Comment by MyfanwyNixon** [comment]
Not sure where it arose from! Happy to drop the distinction and it reads a lot better without. Although now the repetition of 'crowdsourcing' and 'source' begins to bother me. How about:

> Crowdsourcing open, reliable gender data on the world's politicians.

**Comment by tmtmtmtm** [comment]
Looks good to me.

**Comment by chrismytton** [comment]
👍  Thanks @wrightmartin! (and apologies for the delay merging)

**Pull request merged**
