### PR TITLE
Always try to fetch latest incomplete legislature

### LINKED ISSUE #244: Faroe Islands incomplete, but claiming to be
screen shot 2015-08-08 at 12 22 20

screen shot 2015-08-08 at 12 22 57

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #244.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Well detected, thanks! Will merge tomorrow morning.

**Comment by chrismytton** [comment]
Good catch! Thanks @andylolz :tada:

**Comment by chrismytton** [comment]
This has now been deployed to production.

**Comment by andylolz** [comment]
Coooool – thanks!

**Pull request merged**
