### PR TITLE
Add a featured country to the countries page

### LINKED ISSUE #284: Featured Country
We should have a way to 'feature' a country that we particularly want people to play: initially this could simply be the country that has been least played so far.

### PR DESCRIPTION
**Pull request by chrismytton**
This allows us to choose a country which is lacking data. This is then shown in its own section at the top of the countries list.

screen shot 2015-09-29 at 10 02 13

Fixes #284

### CODE REVIEW

**Comment by chrismytton** [comment]
@MyfanwyNixon We could do with a bit of copy to go under the "Featured country" heading in the screenshot above explaining what it is.

As a bit of background we've started with Guatemala as the featured country because we don't have much data for that country and it's one of the least played countries on gender balance so far.

**Comment by MyfanwyNixon** [comment]
How about:

> Poor [Country name] hasn't been played much yet. Give it a whirl?

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon — yep, that sounds good. We're about to add the feature that you get double points for playing it too, so maybe worth adding something about that in?

**Comment by MyfanwyNixon** [comment]
OK then, so:

> Poor [Country name] hasn't been played much yet. Give it a whirl? We'll make it worth your while with **double points**.

**Comment by andylolz** [comment]
One thing about adding an adjective before the country name is the article problem:
https://github.com/everypolitician/viewer-sinatra/issues/611
I guess it would correctly become e.g. “The poor Gambia …”

Also (possibly daft, but) I do find myself first thinking of economic prosperity when I read “poor” in the context of a country.

**Comment by MyfanwyNixon** [comment]
@andylolz Both good points :(
We could change it to 'Aww... [country name]' etc.

**Comment by chrismytton** [comment]
I've added the updated copy and made it so you now get double points if you play a featured country.

screen shot 2015-09-29 at 13 16 10

**Comment by chrismytton** [comment]
Thanks for the copy and suggestions @MyfanwyNixon, @tmtmtmtm and @andylolz!

**Comment by tmtmtmtm** [comment]
Woot! @MyfanwyNixon is it worth putting out a blog post about this? Another follow-up to the "yep, we have LOTS of countries now" with an added "but we've noticed that some get played much more than others, which isn't as useful for those poor researchers looking for data in the less popular places", to re-stress that it's not just about the fun aspect, but that the data is also super-helpful etc?

**Comment by MyfanwyNixon** [comment]
Yes, good idea, will do.

**Comment by chrismytton** [comment]
This is now live on http://www.gender-balance.org/countries and set to Guatemala. I've also added [some instructions to the README about setting the featured country](https://github.com/everypolitician/gender-balance#setting-the-featured-country).

**Comment by andylolz** [comment]
Looks great!

**Comment by MevanBabakar** [comment]
I only search for images when its a few missing out of a set, when there are a bunch in a row I don't bother. It breaks the trance-like flow (!)

When I do search for an image I find I: press the "Google them" link > go to images > make a judgement based on the images. Could you possibly make the google them link go straight to images to save me a click? That would be a small quick fix that'd prob help.

Also if there was an area where I could help populate images, I would probably do that as a separate task. 

Finally - hey everyone!

**Comment by tmtmtmtm** [comment]
@andylolz part of what I'd like to track with this is whether it _is_ because they're actually harder, or just because these are countries that people just don't think to play.

@MevanBabakar I suspect a lot of people do indeed do likewise, but as we stress that people *shouldn't* be guessing based on name or appearance, I fear that linking directly to the image search would send the wrong message…

> Also if there was an area where I could help populate images, I would probably do that as a separate task. 

Hmmm. Interesting idea. I'm not sure what that would look like, but it's definitely one for further thought/discussion!

**Comment by MevanBabakar** [comment]
@tmtmtmtm sure, I understand - when I'm not sure I look at the wiki page - could you maybe just pull in the first paragraph of their wiki (if they have one) to the page? ...I can also stop spewing out loads of ideas as I can appreciate its not very productive if not introduced in the proper way. (#githubnoob)

**Comment by tmtmtmtm** [comment]
@MevanBabakar no, no — spew out as many ideas as you have! :) I can merrily move them to new tickets etc easily enough if needed!

We do already have a ticket about linking to Wikipedia instead of Google if we know that: https://github.com/everypolitician/gender-balance/issues/131 — it's probably one we should look at again.

**Comment by andylolz** [comment]
> Also if there was an area where I could help populate images, I would probably do that as a separate task. 

This probably relates to the image upload / moderation on YourNextRepresentatitve. A takehome from that was that no-one understands image licensing (is that fair, @mhl?) I am excited for this sort of thing in future versions of everypolitician!

**Comment by MevanBabakar** [comment]
I think the thing I would appreciate most tbh is just knowing which ones have pictures and which ones don't. I find myself clicking superfluously a lot at the beginning just to find a good batch that I can play through. It would be great if you could say for each country in the list "90% of these have images" or something jazzier.

**Pull request merged**
