### PR TITLE
Replace female/male with woman/man in interface

### LINKED ISSUE #272: Replace female/male with woman/man where it appears on the interface
Suggestion from @emmajane: https://twitter.com/emmajanehw/status/641563916355653632

screen shot 2015-09-09 at 12 37 09

I wonder if this should also be changed in code? (Possibly not in the database, though.)

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #272.

NB This doesn’t address the use of female/male in code. A separate issue
should be created to address that.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
:+1: looks good to me

**Comment by tmtmtmtm** [comment]
Thanks a lot for this @andylolz  — now deployed.

**Comment by andylolz** [comment]
No prob. Biiiit concerned I have bodged the colours in the animated gif… (I used GIMP, and I have no idea what I’m doing.)

**Comment by tmtmtmtm** [comment]
The orange looks a little duller to me, but I don't think it's a huge issue. I'll leave it up to @zarino to decide whether to replace it again or not.

**Comment by zarino** [comment]
The orange is duller, but I don't think it's worth the effort to fix.

Remember there's also a copy of this gif in the everypolitician repo, used as an advert at the bottom of every country page:

https://github.com/everypolitician/viewer-sinatra/blob/8da31dd9b99bf819a938c90aabbe0eec2e90b783/public/images/screencast.gif

**Comment by andylolz** [comment]
Bah, I didn’t think of that. Thanks @zarino.

**Pull request merged**
