### PR TITLE
Add “Google them!” to the tutorial

### LINKED ISSUE #239: Add a “How to find out the answer” bit to the tutorial
I can’t speak for others, but I know the genders of only a tiny fraction of these politicians. The “Not sure? Google them!” button is therefore incredibly useful.

However, it’s not mentioned in the tutorial currently – in fact, it’s not even shown! This makes it incredibly tempting to just use name / photo / title to determine gender (which the current tutorial does caution against).

### PR DESCRIPTION
**Pull request by andylolz**
Fixes #239.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks for this, @andylolz!

I have a slight hesitation over the "Or you can press the “Google them” button to discover the answer." wording, though. There will quite often be times when Googling reveals nothing useful (or, at least, not from the pre-canned version of the search) — and indeed, that'll definitely be so for some of the 'people' in the on-boarding game itself!

Maybe something more along the lines of "If you don't know, you could try the 'google them' button". Maybe @MyfanwyNixon can give us something snazzy here?

**Comment by andylolz** [comment]
You’re right – good point.

Screenshot of the card as it currently stands (in case that’s helpful):
screen shot 2015-08-20 at 08 53 42

**Comment by MyfanwyNixon** [comment]
> Or maybe Google has the answer -- there's a button for that. Try it for the next person!

**Comment by chrismytton** [comment]
@andylolz This looks great, thanks! Can you squash down the !fixup commit then I'll merge in. :smiley:

**Comment by andylolz** [comment]
Cool :) all squashed now

**Comment by chrismytton** [comment]
Awesome, thanks @andylolz! :tada:

**Comment by chrismytton** [comment]
This is now live. You *might* need to clear your cookies to be able to get to the onboarding screen if you've already been through it.

**Pull request merged**
