### PR TITLE
Escape double quotes in person name and ID

### LINKED ISSUE #281: Escape double quotes in politician names
Refs #279.

Unescaped double quotes in names can break the `politician_id` as well as the “google them” link.

See this example from [the Falkland Islands data](https://github.com/everypolitician/everypolitician-data/blob/c729b00d/data/Falkland_Islands/Assembly/term-1989.csv#L4):

screen shot 2015-09-17 at 08 41 32

Incidentally, no error is thrown when a response is given for this politician, despite the POSTed `politician_id` being incorrect.

### PR DESCRIPTION
**Pull request by andylolz**
I’m not exactly sure if/why this is correct! It seems to work, though.

Fixes #281 & #279.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Oh, very nice! Where did you discover the `<%==`? I can't find it documented anywhere.

**Comment by andylolz** [comment]
Here: http://www.kuwata-lab.com/erubis/users-guide.02.html#tut-escape

**Comment by tmtmtmtm** [comment]
Ah, I didn't actually realise we were using erubis — I thought we were on plain ERB!

**Comment by andylolz** [comment]
Well, it seems to be [via tilt](https://github.com/everypolitician/gender-balance/blob/90e8c88a/app.rb#L5), which appears to [be unescaped by default](https://github.com/rtomayko/tilt/blob/432ae805/lib/tilt/erubis.rb#L12). I am guessing a bit here!

**Comment by chrismytton** [comment]
Ah this is interesting, in vagrant it appears Sinatra is using erubis, because it's installed in the vagrant box via apt (I guess it comes pre-installed on the base box?).

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ gem which erubis
/usr/lib/ruby/vendor_ruby/erubis.rb
```

However it's not installed on Heroku, so presumably there it actually *is* using ERB, and therefore this patch won't work as-is.

```
$ heroku run gem which erubis
Running `gem which erubis` attached to terminal... up, run.8410
ERROR:  Can't find ruby library file or shared library erubis
```

So there are two options I think:

1. Use the escaping method [recommended in Sinatra's FAQ](http://www.sinatrarb.com/faq.html#escape_html)
2. Add erubis to the Gemfile so this patch will work on Heroku

I like option 1. because it's less surprising to those that might already know Sinatra (I also didn't know about the `<%== ` notation in erubis). However I also like option 2. because it seems sensible to be running the same template engine in development and production.

Perhaps there is a third option where we add `erubis` to the Gemfile to keep dev/production consistent *but* we switch to using the Sinatra recommended way of escaping?

**Comment by chrismytton** [comment]
Ignore me, I was running these commands in completely the wrong terminal window! `erubis` is already in the Gemfile so this seems like a reasonable solution, though I wonder if doing it the Sinatra way would be less surprising?

**Comment by tmtmtmtm** [comment]
I'd probably go for option 2 — Erubis isn't _that_ esoteric (AIUI it's the default .erb handler in Rails, and the [next suggestion](http://www.sinatrarb.com/faq.html#auto_escape_html) in the Sinatra FAQ is for using it…

**Comment by chrismytton** [comment]
Yep agreed, and since option 2 is already implemented… :+1:

**Comment by chrismytton** [comment]
Deployed to production!

**Pull request merged**
